const NOTIFICATION_TYPES = {
  FRIENDSHIP_REQUEST: "FRIENDSHIP_REQUEST",
  FRIENDSHIP_REFUSED: "FRIENDSHIP_REFUSED",
  FRIENDSHIP_ACCEPTED: "FRIENDSHIP_ACCEPTED",
  NEW_MESSAGE: "NEW_MESSAGE"
};

module.exports = {
  NOTIFICATION_TYPES
}